options:
  merge-default-rules: true
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholders-in-extend: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-invalid-hex: 2
  one-declaration-per-line: 2
  no-warn: 0
  no-debug: 2
  no-ids: 2
  no-important: 2
  function-name-format:
    - 2
    -
      convention: hyphenatedlowercase
  variable-name-format:
    - 2
    -
      convention: hyphenatedlowercase
  space-after-bang:
    - 2
    -
      include: false

  space-after-colon:
    - 2
    -
      include: false

  space-after-comma:
    - 2
    -
      include: false
  space-around-operator:
    - 2
    -
      include: true
  space-before-bang:
    - 2
    -
      include: true
  space-before-colon:
    - 2
    -
      include: false
  space-before-brace:
    - 2
    -
      include: true
  space-between-parens:
    - 2
    -
      include: false
  trailing-semicolon:
    - 2
    -
      include: true
  quotes:
    - 2
    -
      style: single
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 2
